name: 📦 Release
on:
  milestone:
    types: [closed]
jobs:
  release:
    name: 📝 Draft Release
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Create draft release from milestone
        uses: quaternionmedia/milestones@v0.5.0
